import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const logo = 'https://bitesites.org/_next/image?url=%2Fmainlogo2.png&w=3840&q=75';

const aiSolutions = [
  ['✦', 'AI Receptionists', 'A voice or chat agent that answers every call and message, books appointments, and routes real leads to your team — even after hours.'],
  ['ϟ', 'Custom AI Automation', 'Workflow builds connecting your CRM, forms, and inbox — so leads move automatically and nothing falls through the cracks.'],
  ['◉', 'Custom AI Projects', 'Purpose-built AI tools scoped to your business — from internal ops assistants to full custom systems, built end to end.']
];

const services = [
  { key: 'ai', badge: 'Lead service', title: 'AI Automation', text: 'We identify repetitive work across sales, marketing, and operations, then build AI-assisted workflows that move information faster.', bullets: ['Faster response times for new leads and requests', 'Less repetitive admin work across sales and ops', 'Cleaner handoffs between forms, inboxes, and systems'] },
  { key: 'web', title: 'Web Development', text: 'Websites that turn your online presence into a working sales asset, from strategy and UX to responsive development and launch support.', bullets: ['A stronger first impression that builds credibility', 'Clearer paths to consultations, quotes, or sales', 'Better speed, mobile experience, and search readiness'] },
  { key: 'social', title: 'Social Media Management', text: 'Content planning, publishing, and reporting that keeps your brand active and consistent.', bullets: ['A consistent publishing cadence that keeps you visible', 'Stronger alignment between social, web, and campaigns', 'Higher-quality engagement from the right audience'] }
];

const projects = [
  { title: 'Nexus Verium', video: 'https://bitesites.org/portfolio/nexusverium.mp4', text: 'Restoration systems & environmental engineering — integrating AI and environmental science to heal ecosystems through the River Veins initiative.', bullets: ['River Veins monitoring network — floating AI wetlands, sensors, drones', 'Digital twin models of the Meadowlands for planning', 'Continuous AI-driven water quality analysis'], stack: ['Next.js', 'Tailwind CSS', 'Turbopack'], url: 'https://nexusverium.tech' },
  { title: "These Freakin' Empanadas & More", video: 'https://bitesites.org/portfolio/freakinempanadas.mp4', text: "Bold, crispy, freakin' delicious — a Wood-Ridge empanada hub built to sell hand-held flavor bombs and sandwiches online and in-store.", bullets: ['Full menu with classics, cannoli, spinach artichoke, and General Tso’s chicken', 'Combos and family packs built into ordering', 'Takeout, delivery, and Uber Eats integration'], stack: ['React', 'Tailwind CSS', 'Vite', 'Uber Eats API'], url: 'https://freakinempanadas.com' },
  { title: 'Rutgers Newark Bodega Project', video: 'https://bitesites.org/portfolio/BodegaProject.mp4', text: 'Sustainable food supply chains — a data-informed, hyperlocal network linking local farms and school gardens to Newark’s bodegas.', bullets: ['“Fast vs. Fresh Food” interactive map and KPI builder', 'Data visualization tools for research and community outreach', 'Promotes indoor vertical farming for year-round production'], stack: ['Vite', 'Chart.js', 'Leaflet', 'Mapbox'], url: 'https://jjimenez723.github.io/Bodega-Project-2' }
];

const prices = {
  web: [['Starter Site', 'A sharp single-page site for early-stage launches or service businesses that need credibility fast.', 'From $1,000', ['Single-page site', 'Responsive design', 'Basic SEO', 'One revision']], ['Growth Site', 'A stronger marketing site built around your offer, content, and lead flow.', 'From $2,500', ['Up to 7 pages', 'Conversion-focused UX', 'Analytics setup', 'Two revisions'], true], ['Custom Build', 'A flexible site for businesses with more complex content, integrations, or workflows.', 'Let’s talk', ['Custom architecture', 'Integrations', 'Advanced SEO', 'Ongoing support']]],
  social: [['Essential', 'A consistent publishing rhythm for one channel and a clear brand voice.', 'From $600/mo', ['Content calendar', '8 posts per month', 'Captions and scheduling', 'Monthly report']], ['Growth', 'A complete content engine built around campaigns and measurable goals.', 'From $1,200/mo', ['2 social channels', '16 posts per month', 'Community support', 'Strategy review'], true], ['Custom', 'Multi-channel management for brands with more volume, locations, or approvals.', 'Let’s talk', ['Custom cadence', 'Campaign support', 'Reporting dashboard', 'Creative direction']]],
  ai: [['Workflow Audit', 'Find the manual bottlenecks worth solving first.', 'From $750', ['Process mapping', 'Opportunity scorecard', 'Automation roadmap', 'Implementation plan']], ['Automation Build', 'Build and launch the highest-impact workflow for your team.', 'From $2,000', ['Workflow architecture', 'Tool integrations', 'AI-assisted steps', 'Testing and handoff'], true], ['Custom System', 'Purpose-built AI products and systems for complex operating needs.', 'Let’s talk', ['Custom AI workflow', 'Human review points', 'Documentation', 'Ongoing optimization']]]
};

const detailCopy = {
  web: ['Web Development', 'We design and build websites that turn your online presence into a working sales asset.', ['Custom site architecture, design direction, and page planning', 'Responsive development for desktop, tablet, and mobile', 'Lead forms, CRM hooks, analytics, and conversion tracking', 'Performance, accessibility, and technical SEO foundations', 'CMS or editable sections for your team', 'Launch support, QA, and optimization recommendations']],
  social: ['Social Media Management', 'We manage the planning, production, and publishing rhythm behind your social channels so your brand stays visible and credible.', ['Monthly content planning tied to your priorities', 'Platform-specific post copy, creative direction, and scheduling', 'Brand voice guidance for consistency', 'Community management support', 'Performance reporting and recommendations', 'Coordination with website and campaign activity']],
  ai: ['AI Automation', 'We identify repetitive work across sales, marketing, and operations, then build AI-assisted workflows that reduce manual effort and move information faster.', ['Workflow mapping to identify high-friction tasks', 'Automation design for intake, lead routing, and alerts', 'AI-assisted summarization, categorization, and response support', 'Integrations across forms, email, CRM, and project systems', 'Fallback logic, QA, and human-review checkpoints', 'Documentation so your team can maintain the system']]
};

function Button({ children, variant = 'primary', href, ...props }) { return href ? <a className={`btn btn-${variant}`} href={href} {...props}>{children}</a> : <button className={`btn btn-${variant}`} {...props}>{children}</button>; }
function Eyebrow({ children, gradient = false }) { return <div className={`eyebrow ${gradient ? 'gradient' : ''}`}>{children}</div>; }
function SectionHead({ label, title, children, gradient = false }) { return <div className="section-head reveal"><Eyebrow gradient={gradient}>{label}</Eyebrow><h2>{title}</h2>{children && <p>{children}</p>}</div>; }

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [tab, setTab] = useState('web');
  const [modal, setModal] = useState(null);
  const [status, setStatus] = useState({ text: '', kind: '' });

  useEffect(() => {
    const header = document.querySelector('header');
    const onScroll = () => header.classList.toggle('scrolled', window.scrollY > 12);
    window.addEventListener('scroll', onScroll, { passive: true });
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('in'); observer.unobserve(entry.target); } }), { threshold: .12 });
    document.querySelectorAll('.reveal').forEach(node => observer.observe(node));
    return () => { window.removeEventListener('scroll', onScroll); observer.disconnect(); };
  }, []);

  const closeMenu = () => setMenuOpen(false);
  const submit = async event => {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const payload = Object.fromEntries(data.entries());
    payload.services = data.getAll('services');
    if (!payload.services.length) return setStatus({ text: 'Please select at least one service.', kind: 'error' });
    if (payload.preferredContactMethod === 'phone' && !payload.phone.trim()) return setStatus({ text: 'Please include a phone number if you prefer a phone call.', kind: 'error' });
    setStatus({ text: 'Sending…', kind: '' });
    try { const response = await fetch('/api/lead', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error); form.reset(); setStatus({ text: 'Thanks — your project request has been received. We’ll be in touch soon.', kind: 'success' }); } catch (error) { setStatus({ text: error.message || 'Unable to submit the form. Please try again.', kind: 'error' }); }
  };

  return <>
    <header><nav><a href="#top" className="brand" onClick={closeMenu}><img src={logo} alt="BiteSites" /></a><div className={`navlinks ${menuOpen ? 'open' : ''}`}>{[['Services','#services'],['Portfolio','#portfolio'],['Pricing','#pricing'],['About','#about'],['Consultation','#consultation']].map(([label, href]) => <a key={label} href={href} onClick={closeMenu}>{label}</a>)}</div><div className="navcta"><Button href="#start" variant="ai">Start Your Project</Button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? '×' : '☰'}</button></div></nav></header>
    <main id="top">
      <section className="hero"><div className="hero-bg"><div className="glow" /></div><div className="wrap"><Eyebrow gradient>AI-powered digital solutions</Eyebrow><h1>Intelligence built<br />into your <span className="gradient-text">business.</span></h1><p className="lead">BiteSites helps businesses grow with websites, social media management, and AI automation that solves the work slowing your team down.</p><div className="hero-actions"><Button href="#start" variant="ai">Start Your Project</Button><Button href="#services" variant="ghost">Explore Services</Button></div><div className="hero-meta"><div><span>Web</span> development</div><div><span>Social</span> media management</div><div><span>AI</span> automation</div></div></div></section>
      <div className="strip"><div className="wrap"><span>Web Development</span><span>Social Media Management</span><span>AI Automation</span></div></div>
      <section className="pad" id="ai"><div className="wrap"><SectionHead label="Our focus" title="AI that actually runs your business." gradient>This is where we spend most of our time now — designing AI systems that answer the phone, qualify leads, and handle repetitive work, so your team doesn’t have to.</SectionHead><div className="ai-grid">{aiSolutions.map(([icon, title, text]) => <article className="ai-card reveal" key={title}><div className="ai-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="pad alt" id="services"><div className="wrap"><SectionHead label="What we do" title="Digital services built around growth, not filler.">Three connected service lines that help businesses build a stronger presence, reach the right people, and reduce the manual work holding growth back.</SectionHead><div className="services-grid">{services.map((service, index) => <article className={`service-card reveal ${index === 0 ? 'featured' : ''}`} key={service.key}>{service.badge && <span className="service-badge">{service.badge}</span>}<div className="service-icon">{['✦','□','↻'][index]}</div><h3>{service.title}</h3><p className="desc">{service.text}</p><ul>{service.bullets.map(item => <li key={item}>{item}</li>)}</ul><button className="text-link" onClick={() => setModal(service.key)}>Explore {service.title} →</button></article>)}</div><div className="segments reveal">{[['Small business','Build a credible online presence, stay visible, and reduce repetitive admin work without adding complexity.'],['Medium business','Connect campaigns, service lines, and internal workflows as growing volume creates more moving parts.'],['Large business','Coordinate more stakeholders and more complex processes without sacrificing speed.']].map(([title, text]) => <div className="segment" key={title}><div className="tag">{title}</div><p>{text}</p></div>)}</div></div></section>
      <section className="pad" id="portfolio"><div className="wrap"><SectionHead label="Featured work" title="A curated look at what we’ve shipped.">Real projects for real businesses — crafted with precision, passion, and purpose.</SectionHead><div className="portfolio-list">{projects.map((project, index) => <article className={`project-card reveal ${index % 2 ? 'reverse' : ''}`} key={project.title}><div className="project-media"><video autoPlay muted loop playsInline preload="metadata"><source src={project.video} type="video/mp4" /></video></div><div className="project-body"><h3>{project.title}</h3><p className="desc">{project.text}</p><ul>{project.bullets.map(item => <li key={item}>{item}</li>)}</ul><div className="stack-pills">{project.stack.map(item => <span className="pill" key={item}>{item}</span>)}</div><a className="text-link blue" href={project.url} target="_blank" rel="noreferrer">Visit Website ↗</a></div></article>)}</div></div></section>
      <section className="pad alt" id="pricing"><div className="wrap"><SectionHead label="Pricing" title="Packages built to scale with you.">Compare scope quickly and move into the right engagement without guesswork. Custom quotes are available for hybrid or larger rollouts.</SectionHead><div className="tabbar reveal">{[['web','Web Development'],['social','Social Media'],['ai','AI Automation']].map(([key, label]) => <button className={`tabbtn ${tab === key ? 'active' : ''}`} onClick={() => setTab(key)} key={key}>{label}</button>)}</div><div className="price-grid">{prices[tab].map(([title, desc, price, items, popular]) => <article className={`price-card reveal ${popular ? 'popular' : ''}`} key={title}>{popular && <span className="badge">Popular</span>}<h4>{title}</h4><p className="plandesc">{desc}</p><div className="price">{price}</div><div className="pricenote">{tab === 'social' ? 'monthly engagement' : 'project scope'}</div><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><Button href="#start" variant="ghost">Start Project</Button></article>)}</div><p className="pricing-note">All packages are starting points. We’ll tailor scope to your goals, timeline, and existing tools.</p></div></section>
      <section className="pad" id="about"><div className="wrap"><SectionHead label="About BiteSites" title="Small team. Serious digital work.">We combine thoughtful design, practical engineering, and emerging AI tools to help businesses move forward.</SectionHead><div className="mission reveal"><p>We believe technology should make your business feel lighter — clearer systems, better experiences, and less work lost in the cracks.</p></div><div className="values-grid">{[['Passion for Excellence','Exceptional websites and systems that make a lasting impact.'],['Timely Delivery','We respect your time and deliver projects on schedule.'],['Open Communication','Transparent updates that keep you informed every step of the way.'],['Innovation','We explore new technologies and design trends to stay ahead.']].map(([title, text]) => <div className="value-item reveal" key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
      <section className="pad alt" id="consultation"><div className="wrap"><SectionHead label="Consultation" title="Let’s talk through what your business needs.">Tell us what you are trying to solve. We’ll recommend the right service direction and follow up to confirm a conversation.</SectionHead><div className="segments reveal" style={{ marginTop: 0 }}>{[['01 · Tell us what you need','Share your business, goals, preferred services, and the best way to contact you.'],['02 · We review the scope','We identify the right service mix and prepare practical next steps.'],['03 · We follow up','If the fit is right, we confirm the consultation details with you directly.']].map(([title, text]) => <div className="segment" key={title}><div className="tag">{title}</div><p>{text}</p></div>)}</div><div className="hero-actions reveal"><Button href="https://calendar.app.google/bKKKvGWBSgvV8rodA" variant="ai" target="_blank" rel="noreferrer">Schedule a free consultation</Button><Button href="#pricing" variant="ghost">See pricing</Button></div></div></section>
      <section className="intake" id="start"><div className="wrap intake-grid"><div className="section-head reveal"><Eyebrow gradient>Start your project</Eyebrow><h2>Tell us what you need.</h2><p>Use one form for web development, social media management, or AI automation. We only ask for the details needed to route your project and follow up.</p></div><form className="intake-form reveal" onSubmit={submit}><div className="form-row"><Field label="Name" name="name" required /><Field label="Email" name="email" type="email" required /></div><div className="form-row"><Field label="Phone (optional)" name="phone" type="tel" /><Field label="Business / Company (optional)" name="businessName" /></div><div className="form-row"><Field label="Role in company (optional)" name="roleInCompany" /><label className="field"><span>Business size</span><select name="businessSize" required defaultValue=""><option value="" disabled>Select size</option><option value="solo">Solo / Freelancer</option><option value="small">2-10 employees</option><option value="growing">11-50 employees</option><option value="established">51-200 employees</option><option value="enterprise">200+ employees</option></select></label></div><label className="field"><span>Timeline (optional)</span><select name="urgencyTag" defaultValue=""><option value="">No urgency selected</option><option value="asap">ASAP</option><option value="2_4_weeks">2-4 weeks</option><option value="1_2_months">1-2 months</option><option value="flexible">Flexible</option></select></label><fieldset className="field"><legend>Services <small>(select all that apply)</small></legend><div className="choices">{[['web_development','Web Development'],['social_media_management','Social Media Management'],['ai_automation','AI Automation']].map(([value, label]) => <label className="choice" key={value}><input type="checkbox" name="services" value={value} />{label}</label>)}</div></fieldset><fieldset className="field"><legend>Preferred contact method</legend><div className="choices"><label className="choice"><input type="radio" name="preferredContactMethod" value="email" defaultChecked />Email</label><label className="choice"><input type="radio" name="preferredContactMethod" value="phone" />Phone</label></div></fieldset><label className="field"><span>Project details</span><textarea name="projectDetails" placeholder="What are you looking to accomplish?" /></label><Button variant="ai" type="submit">Start Your Project</Button><p className={`form-status ${status.kind}`}>{status.text}</p></form></div></section>
      <section className="pad"><div className="wrap"><div className="cta-final reveal"><Eyebrow>Get started</Eyebrow><h2>Ready to build what is next?</h2><p>Tell us what you need, choose services, and let us know how you want to be contacted.</p><div className="hero-actions"><Button href="#start" variant="ai">Start Your Project</Button><Button href="#pricing" variant="ghost">View Pricing</Button></div></div></div></section>
    </main>
    <footer><div className="wrap footer-inner"><a href="#top" className="brand"><img src={logo} alt="BiteSites" /></a><div className="footer-links"><a href="#services">Services</a><a href="#about">About</a><a href="#pricing">Pricing</a><a href="#start">Start a Project</a></div><div className="footer-copy">© 2026 BiteSites. All rights reserved.</div></div></footer>
    {modal && <div className="modal-backdrop" onClick={() => setModal(null)}><div className="detail-panel" role="dialog" aria-modal="true" onClick={event => event.stopPropagation()}><button className="close" onClick={() => setModal(null)} aria-label="Close">×</button><div className="detail-hero"><Eyebrow gradient={modal === 'ai'}>Services</Eyebrow><h2>{detailCopy[modal][0]}</h2><p>{detailCopy[modal][1]}</p></div><div className="detail-content"><h3>What’s included</h3><ul className="detail-list">{detailCopy[modal][2].map(item => <li key={item}>{item}</li>)}</ul><div className="hero-actions"><Button href="#start" variant="ai" onClick={() => setModal(null)}>Start Your Project</Button><Button href="#pricing" variant="ghost" onClick={() => setModal(null)}>See pricing</Button></div></div></div></div>}
  </>;
}

function Field({ label, name, type = 'text', required = false }) { return <label className="field"><span>{label}</span><input name={name} type={type} required={required} /></label>; }

createRoot(document.getElementById('root')).render(<App />);
